### ISSUE TITLE
Admin generiert Bestellnummer neu.

### ISSUE THREAD

**Issue by Paminger** [FH-Complete/FHC-AddOn-WaWi#4]
Nachdem die Kostenstelle oder das Geschäftsjahr geändert wurde, kann der Admin die Bestellnummer neu generieren lassen. Auch wenn die Bestellung schon freigegeben ist. Nicht aber wenn die Bestellung bereits bestellt wurde (Status: Bestellung)!!!

**Comment by LordOfTheRams** [comment]
Changes:

- Bei Änderung der Kostenstelle wird nun eine neue Bestellnummer generiert
- Auf mehrfachen Wunsch ist das allerdings auch möglich, **wenn schon bestellt wurde** (Status 'Bestellung')
- Beim Anlegen von Bestellungen kann das Erstellungsdatum ausgewählt werden (wenn man die entsprechende Berechtigung dafür hat). Dadurch kann man Bestellungen für ein anderes Geschäftsjahr erstellen, da das Erstellungsdatum für die Bestellnummer herangezogen wird. Das tatsächliche Geschäftsjahr (DB-Tabelle) ist derzeit (noch?) nicht mir der Bestellung verknüpft.
